# Generated by Django 4.2.5 on 2023-10-06 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='imap_password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='imap_port',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='imap_server',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='imap_username',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='smtp_server',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='smtp_username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_user',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('hashed_password', models.CharField(max_length=128)),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.virtualdomain'),
        ),
    ]
